---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elastic
  - src: git@github.com:jekker600/kibana-role.git
    scm: git
    version: "0.0.4"
    name: kibana_role
  - src: git@github.com:jekker600/filebeat-role.git
    scm: git
    version: "0.0.3"
    name: filebeat_role      
